apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fast57-prometheusrules
spec:
  groups:
  - name: fast57-rules
    rules:
    - alert: HighRequestLatency
      expr: rate(request_latency_bucket[1m]) > 0.05
      for: 5m