apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fast57-rules
spec:
  groups:
  - name: fast57.rules
    rules:
    - alert: HighRequestLatency
      expr: rate(requests{job="fast57"}[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High request latency
